server:
  port: ${PORT:5000}
  contextPath: /uaa

security:
  sessions: if_required

exception:
  message:
    userAlreadyExist: User with login %s already exist
    userNotExist: User with login %s does not exist